services:
  webchat-backend:
    container_name: webchat-backend
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '${PORT}:5000'
    command: npm run start:dev
    depends_on:
      - webchat-postgres
    restart: always
  webchat-postgres:
    container_name: webchat-postgres
    image: postgres:17
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data: